Feature/travel game
lucasvdiepen/ExpandingSpace pull request #4
Opened 2021-05-26 13:10 UTC by ScottZ2004

Added:
- Space ship movement
- random meteor spawning
- A hit animation and retry button
- If you come near to a planet, load the next scene
- A funtion that loads the scene with the given planet as a parameter

2021-05-26 13:28 UTC, BartdeBoer2001 commented on Expanding Space/Assets/Scripts/Planet Spawning/PlanetSpawning.cs
> +            case "Nupetune":
Ik gok dat je 'Neptune' bedoelt?

2021-05-26 14:54 UTC, ScottZ2004 commented on Expanding Space/Assets/Scripts/Planet Spawning/PlanetSpawning.cs
> +            case "Nupetune":
Klopt, bedankt

2021-05-26 19:39 UTC, lucasvdiepen requested changes
Code ziet er goed uit! Met een enum zouden we makkelijker planeten kunnen kiezen zonder de specifieke naam op te zoeken.

2021-05-26 19:39 UTC, lucasvdiepen commented on Expanding Space/Assets/Scripts/Meteorite Spawner/MeteoriteSpawner.cs
> +    public GameObject Meteorite;
Misschien met een kleine letter beginnen

2021-05-26 19:39 UTC, lucasvdiepen commented on Expanding Space/Assets/Scripts/Planet Spawning/PlanetSelection.cs
> +    static public string nameOfPlanet;
Misschien kan voor `nameOfPlanet` een `enum` gebruikt worden. Dat zou er dan zo uit zien: 
```
public static enum Planets
{
    Earth,
    Pluto,
    Mercury,
    enz,
    enz
}

public static Planets nameOfPlanet;
```

2021-05-26 19:39 UTC, lucasvdiepen commented on Expanding Space/Assets/Scripts/Planet Spawning/PlanetSpawning.cs
> +            case "Earth":
Als de `enum` gebruikt wordt kan hier `case PlanetSelection.Planets.Earth:` komen te staan

2021-05-26 19:39 UTC, lucasvdiepen commented on Expanding Space/Assets/Scripts/Ship/Ship hit/ShipHit.cs
> +        switch (planet)
Deze hele `switch` zou vervangen kunnen worden met `SceneManager.LoadScene(planet.ToString());`

2021-05-26 19:39 UTC, lucasvdiepen commented on Expanding Space/Assets/Scripts/Ship/Ship hit/ShipHit.cs
> +    void ShipEntersPlanet(string planet)
Hier zou `string` veranderd moeten worden naar `PlanetSelection.Planets`

2021-05-26 19:39 UTC, lucasvdiepen commented on Expanding Space/Assets/Scripts/Planet Spawning/PlanetSelection.cs
> +    static public void LoadTravelGame(string planet)
Hier zou `string` veranderd moeten worden naar `Planets`

2021-05-26 19:39 UTC, lucasvdiepen commented on Expanding Space/Assets/Scripts/Camera/CameraMovement.cs
> +            movementSpeed += 0.01f;
Misschien van `0.01f` een public float maken zodat we het in de inspector kunnen aanpassen als dat nodig is

2021-06-02 12:10 UTC, lucasvdiepen approved these changes

2021-06-02 13:07 UTC, BartdeBoer2001 approved these changes

2021-06-02 13:18 UTC, merged